CREATE TABLE IF NOT EXISTS notification
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    to_customer_id    BIGINT,
    to_customer_email VARCHAR(255),
    message           VARCHAR(255),
    sender            VARCHAR(255),
    CONSTRAINT pk_notification PRIMARY KEY (id)
);